#!/usr/bin/env python3
"""ROS 2 MuJoCo demo containing only a virtual human force and a free board."""

from __future__ import annotations

import os
import time

import glfw
import mujoco
import mujoco.viewer
import numpy as np
import rclpy
from geometry_msgs.msg import PoseStamped, WrenchStamped
from rclpy.executors import ExternalShutdownException
from rclpy.node import Node


class HumanBoardSim(Node):
    """Apply a virtual human wrench directly to a board in MuJoCo."""

    def __init__(self) -> None:
        super().__init__("human_board_sim")

        self.declare_parameter(
            "model_path",
            "/workspace/unitree_mujoco/unitree_robots/pr2/scene_human_board.xml",
        )
        self.declare_parameter("use_viewer", bool(os.environ.get("DISPLAY", "").strip()))
        self.declare_parameter("force_x", 0.0)
        self.declare_parameter("force_y", 0.0)
        # A negative value selects exact gravity compensation.
        self.declare_parameter("force_z", -1.0)
        self.declare_parameter("hand_offset", 1.0)
        self.declare_parameter("allow_rotation", False)
        self.declare_parameter("publish_rate_hz", 50.0)
        self.declare_parameter("duration", 0.0)

        model_path = str(self.get_parameter("model_path").value)
        self._use_viewer = bool(self.get_parameter("use_viewer").value)
        self._allow_rotation = bool(self.get_parameter("allow_rotation").value)
        self._duration = float(self.get_parameter("duration").value)
        self._publish_period = 1.0 / max(
            float(self.get_parameter("publish_rate_hz").value), 1.0
        )

        self._model = mujoco.MjModel.from_xml_path(model_path)
        self._data = mujoco.MjData(self._model)
        self._board_id = mujoco.mj_name2id(
            self._model, mujoco.mjtObj.mjOBJ_BODY, "board"
        )
        if self._board_id < 0:
            raise RuntimeError(f'body "board" not found in {model_path}')

        requested_force_z = float(self.get_parameter("force_z").value)
        force_z = (
            self._model.body_mass[self._board_id]
            * abs(float(self._model.opt.gravity[2]))
            if requested_force_z < 0.0
            else requested_force_z
        )
        self._force = np.array(
            [
                float(self.get_parameter("force_x").value),
                float(self.get_parameter("force_y").value),
                force_z,
            ],
            dtype=np.float64,
        )
        self._hand_offset = np.array(
            [float(self.get_parameter("hand_offset").value), 0.0, 0.0],
            dtype=np.float64,
        )

        self._pub_pose = self.create_publisher(PoseStamped, "board_pose", 10)
        self._pub_wrench = self.create_publisher(
            WrenchStamped, "virtual_human/hand_wrench", 10
        )
        self._next_publish_time = 0.0

        mujoco.mj_forward(self._model, self._data)
        self.get_logger().info(
            "human-board simulation ready: "
            f"mass={self._model.body_mass[self._board_id]:.3f} kg, "
            f"force={self._force.tolist()} N, "
            f"contact={'point' if self._allow_rotation else 'grip'}, "
            f"model={model_path}"
        )

    def _apply_human_wrench(self) -> np.ndarray:
        board_rotation = self._data.xmat[self._board_id].reshape(3, 3)
        offset_world = board_rotation @ self._hand_offset
        force_moment = np.cross(offset_world, self._force)

        # xfrc_applied stores the net force and torque at the body COM.
        self._data.xfrc_applied[self._board_id, :3] = self._force
        if self._allow_rotation:
            self._data.xfrc_applied[self._board_id, 3:] = force_moment
            return np.zeros(3, dtype=np.float64)

        # A grasp can transmit a moment. The hand moment cancels the moment
        # generated by applying the force away from the board COM.
        grip_moment = -force_moment
        self._data.xfrc_applied[self._board_id, 3:] = force_moment + grip_moment
        return grip_moment

    def _publish_state(self, grip_moment: np.ndarray) -> None:
        stamp = self.get_clock().now().to_msg()

        pose = PoseStamped()
        pose.header.stamp = stamp
        pose.header.frame_id = "world"
        position = self._data.xpos[self._board_id]
        quaternion_wxyz = self._data.xquat[self._board_id]
        pose.pose.position.x = float(position[0])
        pose.pose.position.y = float(position[1])
        pose.pose.position.z = float(position[2])
        pose.pose.orientation.w = float(quaternion_wxyz[0])
        pose.pose.orientation.x = float(quaternion_wxyz[1])
        pose.pose.orientation.y = float(quaternion_wxyz[2])
        pose.pose.orientation.z = float(quaternion_wxyz[3])
        self._pub_pose.publish(pose)

        wrench = WrenchStamped()
        wrench.header.stamp = stamp
        wrench.header.frame_id = "world"
        wrench.wrench.force.x = float(self._force[0])
        wrench.wrench.force.y = float(self._force[1])
        wrench.wrench.force.z = float(self._force[2])
        wrench.wrench.torque.x = float(grip_moment[0])
        wrench.wrench.torque.y = float(grip_moment[1])
        wrench.wrench.torque.z = float(grip_moment[2])
        self._pub_wrench.publish(wrench)

    def _step_once(self) -> None:
        rclpy.spin_once(self, timeout_sec=0.0)
        grip_moment = self._apply_human_wrench()
        mujoco.mj_step(self._model, self._data)
        if self._data.time >= self._next_publish_time:
            self._publish_state(grip_moment)
            self._next_publish_time += self._publish_period

    def _run_loop(self, viewer=None) -> None:
        while rclpy.ok() and (viewer is None or viewer.is_running()):
            if self._duration > 0.0 and self._data.time >= self._duration:
                break
            step_start = time.perf_counter()
            self._step_once()
            if viewer is not None:
                viewer.sync()
            remaining = self._model.opt.timestep - (
                time.perf_counter() - step_start
            )
            if remaining > 0.0:
                time.sleep(remaining)

    def run(self) -> None:
        if not self._use_viewer:
            self.get_logger().info("running without MuJoCo viewer")
            self._run_loop()
            return

        try:
            viewer_available = bool(glfw.init())
            if viewer_available:
                glfw.terminate()
        except Exception:
            viewer_available = False

        if not viewer_available:
            self.get_logger().error(
                "GLFW viewer unavailable; continuing in headless mode"
            )
            self._run_loop()
            return

        with mujoco.viewer.launch_passive(self._model, self._data) as viewer:
            viewer.cam.type = mujoco.mjtCamera.mjCAMERA_FREE
            viewer.cam.lookat[:] = self._data.xpos[self._board_id]
            viewer.cam.lookat[2] *= 0.5
            viewer.cam.distance = 5.0
            viewer.cam.azimuth = 90.0
            viewer.cam.elevation = -18.0
            viewer.sync()
            self.get_logger().info(
                "MuJoCo viewer started; mouse rotate/pan/zoom is enabled"
            )
            self._run_loop(viewer)


def main() -> None:
    rclpy.init()
    node = HumanBoardSim()
    try:
        node.run()
    except (KeyboardInterrupt, ExternalShutdownException):
        pass
    finally:
        node.destroy_node()
        if rclpy.ok():
            rclpy.shutdown()


if __name__ == "__main__":
    main()
